# Model::Definition is the root of the data structure generated by the DSL
# it contains multiple endpoints, which themselves contain multiple (perhaps
# nested) attributes.
module ApiBuddy
  module Model
    class Definition
      attr_reader :endpoints
      attr_accessor :title

      def initialize
        @endpoints = []
      end

      def inspect
        "#<#{self.class} endpoints #{endpoints}>"
      end
      alias_method :to_s, :inspect
    end
  end
end
